# Generated by Django 4.2.11 on 2024-06-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacroeconomicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('real_gdp', models.FloatField()),
                ('growth_rate', models.FloatField()),
                ('fdi', models.FloatField()),
                ('inf', models.FloatField()),
                ('fiscal_expenditure', models.FloatField()),
            ],
        ),
    ]
