# Generated by Django 4.2.11 on 2024-06-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflestApp', '0002_remove_macroeconomicdata_growth_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroeconomicdata',
            name='growth_rate',
            field=models.FloatField(null=True),
        ),
    ]
