# Generated by Django 4.2.11 on 2024-07-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflestApp', '0003_macroeconomicdata_growth_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macroeconomicdata',
            old_name='fdi',
            new_name='broad_money_growth_rate',
        ),
        migrations.RenameField(
            model_name='macroeconomicdata',
            old_name='fiscal_expenditure',
            new_name='fdi_growth_rate',
        ),
        migrations.RenameField(
            model_name='macroeconomicdata',
            old_name='growth_rate',
            new_name='fiscal_expenditure_growth_rate',
        ),
    ]
